###################################################################
#General UI color choices/overrides
###################################################################
[mac]defaultFont = -1

# this controls the ui highlight in dropdowns n'at
[light]@accentColor = #048EFF
[dark]@accentColor= #00BBFF

#@accentFocusColor = saturate(@accentColor, 25%)
@buttonHoverArrowColor = @accentFocusColor
Component.arrowType = chevron
ToggleButton.selectedBackground = lighten(@accentColor, 40%)

MenuItem.textNoAcceleratorGap = 0
MenuItem.acceleratorArrowGap = 2

TabbedPane.tabType = card
TabbedPane.tabsPopupPolicy = asNeeded

###################################################################
# Alice specific variables
###################################################################
Alice.Comment.background = #DDDDDD
Alice.Comment.foreground = #038932

# Objects/Classes instantiated (every this.* and more)
Alice.Instance.color = #FED702

# Types are everywhere
Alice.Type.color = #FFF1BF
Alice.Type.blockColor = changeLightness($Alice.Type.color,77%)

#Gallery folders
[light]Alice.folderColor = #FFF1BF

# this color shows up when editing a constructor, on the scene tab, and in the little folder icons in that one dropdown menu
[light]Alice.Constructor.color = #ddF8ff

# When we make a new object they are a property of the scene, so it actually makes more sense for them to be the same color
Alice.Constructor.blockColor = #FF8D28
# Fields/Parameters/Properties
[light]Alice.Field.color = #FFF1E4
[dark]Alice.Field.color = #ECD0B7

# Procedures
[light]Alice.Procedure.color = #EBEAFF
[dark]Alice.Procedure.color = #BEBCE0
Alice.Procedure.blockColor = #6B5EFF

# Functions
[light]Alice.Function.color = #E2FFE9
[dark]Alice.Function.color = #BFE1C8
Alice.Function.blockColor = #35C759

# Events
[light]Alice.Event.color = #FFFFFF
[dark]Alice.Event.color = #4B4B4B

# Resources (e.g. audio files, image files, etc)
[light]Alice.Resource.color = #FFFFFF
[dark]Alice.Resource.color = #2B2C2F

# (try to remove most of the calls to this. just need it for homebrew elements)
Alice.background = @background

# just to add some variety, this is a softer/less contrasting version of background/foreground
[light]Alice.differentBackground = darken(@background, 15%)
[dark]Alice.differentBackground = lighten(@background, 15%)

[light]Alice.differentForeground = lighten(@foreground, 35%)
[dark]Alice.differentForeground = darken(@foreground, 35%)

# Used to highlight errors, etc
Alice.Alert.color = rgb(170, 0, 0)
[dark]Alice.Alert.color = changeLightness($Alice.Alert.color,60%)

###################################################################
# Draggable Tiles
###################################################################
#default block color
Alice.Block.background = #FFFFFF

# Text/outlines
Alice.Block.foreground = #F2F2F7
# Dots on the edge
Alice.Block.lightKnurlForeground = #D9D9D9
Alice.Block.darkKnurlForeground = #3E3E41

# contrasting text/backgrounds
Alice.Block.contrastForeground = #3E3E41
Alice.Block.contrastBackground = #D9D9D9