###################################################################
#General UI color choices/overrides
###################################################################
defaultFont ="Noto Sans"

# this controls the ui highlight in dropdowns n'at
[light]@accentColor = #048EFF
[dark]@accentColor= #00BBFF

#@accentFocusColor = saturate(@accentColor, 25%)
@buttonHoverArrowColor = @accentFocusColor
Component.arrowType = chevron

TabbedPane.tabType = card
TabbedPane.tabsPopupPolicy = asNeeded

###################################################################
# Alice specific variables
###################################################################
Alice.Comment.Color = #DDDDDD
Alice.Comment.Color.foreground = #038932

# Nouns are Objects/Classes instantiated (every this.* and more)
Alice.Noun.Color = #FED702

# Types are everywhere
Alice.Type.Color = #FFF1BF
Alice.Type.Block.Color = changeLightness($Alice.Type.Color,77%)

#Gallery folders
[light]Alice.Gallery.Folder.Color = #FFF1BF

# this color shows up when editing a constructor, on the scene tab, and in the little folder icons in that one dropdown menu
[light]Alice.Constructor.Color = #ddF8ff

# When we make a new object they are a property of the scene, so it actually makes more sense for them to be the same color
Alice.Constructor.Block.Color = #FF8D28
# Fields/Parameters/Properties
[light]Alice.Field.Color = #FFF1E4
[dark]Alice.Field.Color = #ECD0B7

# Procedures
[light]Alice.Procedure.Color = #EBEAFF
[dark]Alice.Procedure.Color = #BEBCE0
Alice.Procedure.Block.Color = #6B5EFF

# Functions
[light]Alice.Function.Color = #E2FFE9
[dark]Alice.Function.Color = #BFE1C8
Alice.Function.Block.Color = #35C759

# Events
[light]Alice.Event.Color = #FFFFFF
[dark]Alice.Event.Color = #4B4B4B

# Resources (e.g. audio files, image files, etc)
[light]Alice.Resource.Color = #FFFFFF
[dark]Alice.Resource.Color = #2B2C2F

# (try to remove most of the calls to this. just need it for homebrew elements)
Alice.Background.Color = @background

# just to add some variety, this is a softer/less contrasting version of background/foreground
#[light]Alice.Background.Color.different = #CECECE
[light]Alice.Background.Color.different = darken(@background, 15%)
[dark]Alice.Background.Color.different = lighten(@background, 15%)

[light]Alice.Foreground.Color.different = lighten(@foreground, 35%)
[dark]Alice.Foreground.Color.different = darken(@foreground, 35%)

# Used to highlight errors, etc
Alice.Alert.Color = rgb(170, 0, 0)
[dark]Alice.Alert.Color = changeLightness($Alice.Alert.Color,60%)

###################################################################
# Draggable Tiles
###################################################################
# Dots on the edge
Alice.Block.Knurl.Color = #D9D9D9
Alice.Block.Canvas.Color = #FFFFFF

# Text/outlines
Alice.Block.Foreground.Color = #F2F2F7

# contrasting text/backgrounds
Alice.Block.Contrast.Foreground.Color = #3E3E41
Alice.Block.Contrast.Background.Color = #D9D9D9