BackupProjectOperation.BackupLoadErrorAndLoadOriginalDialog.message = WARNING: All backups more recent than the project were corrupted.\nWould you like to reload the original project file (</projectName/>)?
BackupProjectOperation.BackupLoadErrorAndLoadOriginalDialog.title = Reload Original
BackupProjectOperation.BackupLoadErrorDialog.message = This backup was corrupted and could not be loaded.
BackupProjectOperation.BackupLoadErrorDialog.title = Unable to Load Backup
BackupProjectOperation.BackupOpenedDialog.messageWithBackupDate = A backup of </projectName/> from </backupDate/> has been opened successfully.\nWould you like to replace the original project, or create a new project from the backup?
BackupProjectOperation.BackupOpenedDialog.messageWithBackupName = A backup of </projectName/> named </backupName/> has been opened successfully.\nWould you like to replace the original project, or create a new project from the backup?
BackupProjectOperation.BackupOpenedDialog.option1 = Replace Original Project
BackupProjectOperation.BackupOpenedDialog.option2 = Save as New Project
BackupProjectOperation.BackupOpenedDialog.option3 = Return to Original Project
BackupProjectOperation.BackupOpenedDialog.title = Replace Project With Backup?
BackupProjectOperation.BackupsAndOriginalLoadErrorDialog.message = The original project (</mainProjectName/>) and all backups were corrupted, and none could be loaded.
BackupProjectOperation.BackupsAndOriginalLoadErrorDialog.title = Unable to Load Backup
BackupProjectOperation.MoreRecentBackupsDialog.message = WARNING: There is a backup with more recent changes.\nWould you like to load it instead?
BackupProjectOperation.MoreRecentBackupsDialog.title = Load backup?
BackupProjectOperation.ProjectLoadErrorAndLoadBackupDialog.message = WARNING: </projectName/> could not be loaded.\nWould you like to try loading a backup?
BackupProjectOperation.ProjectLoadErrorAndLoadBackupDialog.messageWithBackupDate = WARNING: A backup of </projectName/> from </backupDate/> could not be loaded.\nWould you like to try loading an earlier backup?
BackupProjectOperation.ProjectLoadErrorAndLoadBackupDialog.messageWithBackupName = WARNING: A backup of </projectName/> named </backupName/> could not be loaded.\nWould you like to try loading an earlier backup?
BackupProjectOperation.ProjectLoadErrorAndLoadBackupDialog.title = Load Backup
BackupProjectOperation.UnsavedBackupOpenedDialog.message = WARNING: Backups of an unsaved new project were detected.\nWould you like to load the latest one, or discard all backups?
BackupProjectOperation.UnsavedBackupOpenedDialog.option1 = Load Backup
BackupProjectOperation.UnsavedBackupOpenedDialog.option2 = Discard Backups
BackupProjectOperation.UnsavedBackupOpenedDialog.title = Load Backup of New Project
BackupProjectOperation.UnsavedBackupsLoadErrorDialog.message = All backups of an unsaved new project were corrupted, and none could be loaded.
BackupProjectOperation.UnsavedBackupsLoadErrorDialog.title = Unable to Load Backup
ExitOperation = Exit
ExitOperation.mnemonic = VK_X
ExportProjectOperation = Export...   (beta)
NewProjectOperation = New...
NewProjectOperation.accelerator = VK_N
NewProjectOperation.mnemonic = VK_N
OpenProjectOperation = Open...
OpenProjectOperation.accelerator = VK_O
OpenProjectOperation.mnemonic = VK_O
PotentialClearanceIteratingOperation.message = Your program has been modified.  Would you like to save it?
PotentialClearanceIteratingOperation.title = Save changed project?
RevertProjectOperation = Revert
RevertProjectOperation.mnemonic = VK_R
SaveAsProjectOperation = Save As...
SaveAsProjectOperation.accelerator = VK_S,SHIFT_MASK
SaveAsProjectOperation.mnemonic = VK_A
SaveProjectOperation = Save
SaveProjectOperation.accelerator = VK_S
SaveProjectOperation.mnemonic = VK_S
