/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DoTogetherCustomizer.java
 *
 * Created on Mar 3, 2010, 4:14:02 PM
 */

package org.alice.netbeans.palette.items.views;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.JTextComponent;
import org.alice.netbeans.palette.items.DoTogether;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;

/**
 *
 * @author Administrator
 */
public class DoTogetherCustomizer extends javax.swing.JPanel {

    private Dialog dialog = null;
    private DialogDescriptor descriptor = null;
    private boolean dialogOK = false;

    DoTogether doTogether;
    JTextComponent target;

    /** Creates new form DoTogetherCustomizer */
    public DoTogetherCustomizer(DoTogether doTogether, JTextComponent target) {
        this.doTogether = doTogether;
        this.target = target;

        initComponents();

		this.jSpinner1.setModel( new SpinnerNumberModel( 2, 2, 100, 1) );
    }

    public boolean showDialog() {

        dialogOK = false;

        String displayName = "Do Together";
        descriptor = new DialogDescriptor
                (this, displayName, true,
                DialogDescriptor.OK_CANCEL_OPTION, DialogDescriptor.OK_OPTION,
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        if (descriptor.getValue().equals(DialogDescriptor.OK_OPTION)) {
                            evaluateInput();
                            dialogOK = true;
                        }
                        dialog.dispose();
                    }
        }
        );

        dialog = DialogDisplayer.getDefault().createDialog(descriptor);
        dialog.setVisible(true);
        repaint();

        return dialogOK;

    }

    private void evaluateInput()
    {
        int count = ((Integer)jSpinner1.getValue()).intValue();
        doTogether.setRunnableCount(count);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(DoTogetherCustomizer.class, "DoTogetherCustomizer.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 4, 6);
        add(jLabel1, gridBagConstraints);

        jSpinner1.setMinimumSize(new java.awt.Dimension(39, 20));
        jSpinner1.setPreferredSize(new java.awt.Dimension(39, 20));
        jSpinner1.setValue(new Integer(2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 4, 10);
        add(jSpinner1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

}
