#!/usr/bin/env ruby

require 'fileutils'

def process_dir( directory )
  Dir.new( directory ).each do |file|
    unless ['.', '..'].include? file
      path = directory + "/" + file
      process_dir( path ) if File.directory?( path )

      if File.basename( path ) == ".project" then
        settings_dir = directory + "/.settings" 
        if ( File.exists? settings_dir ) && (File.absolute_path(settings_dir) != File.absolute_path(SETTINGS_DIR) ) then
          puts "copying settings for #{settings_dir}"
          SETTING_FILES.each do |setting|
            FileUtils.cp( SETTINGS_DIR + "/" + setting, settings_dir + "/" + setting )
          end
        end
      end
    end
  end
end

# tools/sync-eclipse-settings core/ide/.settings .
begin
  SETTINGS_DIR = ARGV[0]
  WORKING_DIR = ARGV[1]

  SETTING_FILES = [ "org.eclipse.jdt.core.prefs", "org.eclipse.jdt.ui.prefs" ]

  process_dir( WORKING_DIR )
end

