name: Alice Checkstyle CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Checkstyle with Maven
      run: mvn -B verify checkstyle:checkstyle -Dcheckstyle.config.location=checkstyle.xml
    - uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/checkstyle-result.xml'
